name: Maketest

on: push

jobs:
  build:
    name: "Maketest (cc=${{matrix.cc}}, buildtype=${{matrix.buildtype}}, sanitizer=${{matrix.sanitizer}})"

    strategy:
      fail-fast: false

      matrix:
        cc:
          - gcc
          - clang
        buildtype:
          - debug
          - release
        sanitizer:
          - none
          - thread
          - address
          - leak
          - undefined
          - memory

        exclude:
          - buildtype: release
            sanitizer: thread
          - buildtype: release
            sanitizer: address
          - buildtype: release
            sanitizer: leak
          - buildtype: release
            sanitizer: undefined
          - buildtype: release
            sanitizer: memory
          - cc: gcc
            sanitizer: memory

    runs-on: ubuntu-latest

    container:
      image: ubuntu:latest
      options: --privileged
    env:
      DEBIAN_FRONTEND: noninteractive

    steps:
      - name: Update dependencies
        run: apt-get update

      - name: Install utils
        run: apt-get install -y build-essential binutils binutils-dev libc++-dev libc++abi-dev ${{matrix.cc}} make python3

      - uses: actions/checkout@v4

      - name: Build all
        run: CC=${{matrix.cc}} BUILDTYPE=${{matrix.buildtype}} SANITIZER=${{matrix.sanitizer}} make build

      - name: Test all
        run: CC=${{matrix.cc}} BUILDTYPE=${{matrix.buildtype}} SANITIZER=${{matrix.sanitizer}} make test
